title: TinyUI
email: 81813780@qq.com
url: https://tiny-ui.com
github_username:  HarlonWang

# Build settings
# theme: "just-the-docs"
remote_theme: just-the-docs/just-the-docs

aux_links:
  "Docs on GitHub":
    - "//github.com/Tiny-UI/tiny-ui.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "返回"
